name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js with Volta
      - name: Set up Node.js with Volta
        uses: volta-cli/action@v1
        with:
          node-version: '20.6.1'

      # Install pnpm using Volta (manually)
      - name: Install pnpm via Volta
        run: volta install pnpm@9.10.0

      # Cache pnpm store to speed up builds
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install dependencies using pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Run linter
      - name: Lint
        run: pnpm lint

  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js with Volta
      - name: Set up Node.js with Volta
        uses: volta-cli/action@v1
        with:
          node-version: '20.6.1'

      # Install pnpm using Volta (manually)
      - name: Install pnpm via Volta
        run: volta install pnpm@9.10.0

      # Cache pnpm store to speed up builds
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install dependencies using pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Run tests
      - name: Run Tests
        run: pnpm test
