name: Deploy Ember to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js with Volta
      - name: Set up Node.js with Volta
        uses: volta-cli/action@v1
        with:
          node-version: '20.6.1'  # Node.js version defined in your volta settings

      # Install pnpm using Volta (manually)
      - name: Install pnpm via Volta
        run: volta install pnpm@9.10.0

      # Cache pnpm store to speed up builds
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile  # Use frozen lockfile for consistency

      # Build the Ember app for production
      - name: Build Ember app
        run: pnpm run build -- --environment=production

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
          publish_dir: ./dist  # The directory where the Ember build output is located
          force_orphan: true  # Ensure a clean gh-pages branch is used for deployment
